name: Publish to prod environment

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14]

    steps:
      # - name: Checkout repository
      #   uses: actions/checkout@v4

      # - name: Set up Node.js ${{ matrix.node-version }}
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: ${{ matrix.node-version }}

      # - name: Install dependencies
      #   run: npm install --legacy-peer-deps

      # - name: Build
      #   run: npm run build

      # - name: Install ossutil
      #   run: |
      #     sudo -v ; curl https://gosspublic.alicdn.com/ossutil/install.sh | sudo bash

      # - name: Sync asstes to OSS
      #   env:
      #     ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
      #     ACCESS_KEY_SECRET: ${{ secrets.ACCESS_KEY_SECRET }}
      #   run: |
      #     /usr/bin/ossutil cp -r ./dist oss://tuxun-front --exclude index.html -i $ACCESS_KEY_ID -k $ACCESS_KEY_SECRET -e oss-cn-hangzhou.aliyuncs.com

      # - name: Sync asstes to OSS
      #   env:
      #     ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
      #     ACCESS_KEY_SECRET: ${{ secrets.ACCESS_KEY_SECRET }}
      #   run: |
      #     /usr/bin/ossutil cp -r -f ./dist oss://chaofun-resource -i $ACCESS_KEY_ID -k $ACCESS_KEY_SECRET -e oss-cn-hangzhou.aliyuncs.com

      # - name: Sync html to OSS
      #   env:
      #     ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
      #     ACCESS_KEY_SECRET: ${{ secrets.ACCESS_KEY_SECRET }}
      #   run: |
      #     /usr/bin/ossutil cp -r ./dist/index.html oss://tuxun-front -i $ACCESS_KEY_ID -k $ACCESS_KEY_SECRET -e oss-cn-shanghai.aliyuncs.com

      - name: tansfer and release
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: root
          server: ${{ secrets.SERVER_IP }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} 
          local_path: './README.md'
          remote_path: '/root/front/' 
